### PR TITLE
Binary Search Update

### PR DESCRIPTION
**Pull request by RyanGoudie**
1. I have updated the algorhitm to be more compact and readable

2. I have created a Test Html file to run the Trinket.io emded link in which could be implemented into the page as Dan Suggested.

3. I have created a .txt file with information which would be displayed on the page along side the code , I would have implemented it myself but i am clueless when it comes to JavaScript.

4. I have also left a image given to me by the university which shows how binary search works.

Cheers
Ryan

### CODE REVIEW

**Comment by dl1683** [comment]
Could you link a demo of it working?

**Comment by RyanGoudie** [comment]
[TrinketDemo.zip](https://github.com/datastructures-dev/datastructures-dev.github.io/files/4853028/TrinketDemo.zip)

Unzip and open via browser

**Comment by dl1683** [comment]
image
 That's the result

**Comment by RyanGoudie** [comment]
Screenshot 2020-07-01 at 12 38 06


Strange not sure whats happening , this should be the result

**Comment by dl1683** [comment]
Nothing to be done about it rn. I loved your description tho. Check your Reddit. I've sent you a message about what we should be doing.

**Pull request merged**
